### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by GBellamy**
## Purpose

Adding the online Matchmaking system synced with Firebase. Fixing linting to get in line with the AirBnB code style.

## Approach
Matchmaking now functionnal with rooms system and randomly generated usernames

#### Open Questions and Pre-Merge TODOs
- [x] Fix linting
- [x] Travis checking out

## Learning
Used the LiveCoding video from the Uno game made by our teachers

#### Blog Posts
- [How to Pull Request](https://github.com/flexyford/pull-request) Github Repo with Learning focused Pull Request Template.

## TO VALID PR

* All commits, vars, documentation, code are in English
* 1 feature = 1 PR, No more
* The code builds with Travis CI, and nothing looks unfinished
* When code is complicated, that’s documented, otherwise ask for comment 
* No node_modules is present
* Code respect [Airbnb style](https://hackernoon.com/configure-eslint-prettier-and-flow-in-vs-code-for-react-development-c9d95db07213) checked with Travis CI
* README explain Clearly how to run the project, otherwise reject the PR
* Chrome LightHouse CI score is upper than 80%

### CODE REVIEW

**Review by riderx — CHANGES_REQUESTED** [review]
Need PR description

**Review by GuillaumeCabaret — APPROVED** [review]
that's ok

**Review by LudovicLanchon — APPROVED** [review]
seems good to me !

**Review by riderx — APPROVED** [review]

**Review by BenjaminPerrin — APPROVED** [review]
all good Bra'

**Review by paulMorea — APPROVED** [review]
good

**Pull request merged**
